export interface Producto {
  id: number;
  name: string;
  category: string;
  price: number;
  image: string;
  description: string;
}

const productsData: Producto[] = [
  {
    id: 1,
    name: 'Chocolate Amargo',
    category: 'Chocolatería',
    price: 50,
    image: '/Img/Products/Chocolateria/Chocolate_Amargo.webp',
    description: 'Nuestro Chocolate Amargo es una delicia intensa elaborada con un alto porcentaje de cacao puro, ideal para los verdaderos amantes del chocolate. Su sabor profundo, con notas sutiles de frutos secos y una textura firme que se derrite lentamente en el paladar, lo convierte en la elección perfecta para quienes buscan una experiencia sensorial sofisticada y sin azúcares añadidos.'
  },
  {
    id: 2,
    name: 'Trufas Clásicas',
    category: 'Chocolatería',
    price: 60,
    image: '/Img/Products/Chocolateria/Trufas_Clasicas.webp',
    description: 'Las Trufas Clásicas son pequeñas obras maestras hechas a mano con una mezcla perfecta de ganache suave y cobertura de chocolate amargo espolvoreada con cacao en polvo. Cada bocado es una explosión de sabor cremoso y profundo, que ofrece una experiencia de lujo para los sentidos. Perfectas para regalar o para disfrutar en un momento de indulgencia personal.'
  },
  {
    id: 3,
    name: 'Tableta de Cacao 70%',
    category: 'Chocolatería',
    price: 45,
    image: '/Img/Products/Chocolateria/Tableta-de-Cacao.webp',
    description: 'La Tableta de Cacao 70% es un equilibrio perfecto entre amargor y dulzura, ideal para quienes buscan una experiencia auténtica del cacao. Con ingredientes seleccionados de origen sostenible, esta tableta es rica en antioxidantes, con un aroma profundo y una textura suave que se funde delicadamente en la boca.'
  },
  {
    id: 4,
    name: 'Chocolate con Almendras',
    category: 'Chocolatería',
    price: 55,
    image: '/Img/Products/Chocolateria/Chocolate-con-Almendras.webp',
    description: 'Disfruta de la combinación perfecta entre el sabor del chocolate oscuro y la textura crujiente de almendras tostadas. Esta barra está elaborada con ingredientes de alta calidad y ofrece un contraste delicioso que deleita a cualquier paladar. Un clásico que nunca falla.'
  },
  {
    id: 5,
    name: 'Barras Rellenas',
    category: 'Chocolatería',
    price: 48,
    image: '/Img/Products/Chocolateria/Barras Rellenas.webp',
    description: 'Nuestras Barras Rellenas son una experiencia multisensorial: una capa exterior de chocolate liso y brillante que envuelve un corazón suave y cremoso. Disponibles en una variedad de sabores como avellana, caramelo o fresa, son perfectas para quienes buscan algo más que una barra común.'
  },
  {
    id: 6,
    name: 'Chocolate Blanco',
    category: 'Chocolatería',
    price: 52,
    image: '/Img/Products/Chocolateria/Chocolate_Blanco.webp',
    description: 'El Chocolate Blanco es una delicia cremosa y suave, con un toque de vainilla natural que resalta su dulzura característica. Elaborado con manteca de cacao de alta pureza, este chocolate ofrece una textura sedosa ideal para los más golosos.'
  },
  {
    id: 7,
    name: 'Chocolate con Naranja',
    category: 'Chocolatería',
    price: 53,
    image: '/Img/Products/Chocolateria/Chocolate con naranja.webp',
    description: 'Esta barra combina el intenso sabor del chocolate oscuro con la frescura cítrica de la naranja. El resultado es un equilibrio elegante entre dulzura y acidez, ideal para quienes buscan una experiencia diferente y sofisticada en cada mordida.'
  },
  {
    id: 8,
    name: 'Chocolate con Menta',
    category: 'Chocolatería',
    price: 50,
    image: '/Img/Products/Chocolateria/Chocomenta.webp',
    description: 'Nuestro Chocolate con Menta ofrece una sensación refrescante única, combinando el profundo sabor del chocolate oscuro con la frescura natural de la menta. Perfecto como digestivo o simplemente para disfrutar de un gusto diferente que limpia el paladar.'
  },
  {
    id: 9,
    name: 'Chocolate Artesanal',
    category: 'Chocolatería',
    price: 70,
    image: '/Img/Products/Chocolateria/Chocolate Artesanal.webp',
    description: 'Elaborado a mano con técnicas tradicionales y cacao de origen ético, nuestro Chocolate Artesanal es una verdadera joya culinaria. Cada pieza refleja la pasión y el cuidado en su proceso, logrando un sabor único que no encontrarás en productos industriales.'
  },
  {
    id: 10,
    name: 'Bombones de Chocolate',
    category: 'Chocolatería',
    price: 62,
    image: '/Img/Products/Chocolateria/Bombones_de_Chocolate.webp',
    description: 'Estos bombones están rellenos con los más deliciosos sabores, desde frutas hasta licores, y cubiertos con una delicada capa de chocolate. Ideales para regalar o disfrutar en momentos especiales, su textura y sabor te conquistarán desde el primer bocado.'
  },
  {
    id: 11,
    name: 'Mini Trufas',
    category: 'Chocolatería',
    price: 40,
    image: '/Img/Products/Chocolateria/Mini_Trufas.webp',
    description: 'Pequeñas pero poderosas, nuestras Mini Trufas ofrecen el mismo sabor y suavidad de una trufa clásica, en un tamaño perfecto para disfrutar sin culpa. Ideales para compartir o como un detalle gourmet.'
  },
  {
    id: 12,
    name: 'Chocotejas',
    category: 'Chocolatería',
    price: 65,
    image: '/Img/Products/Chocolateria/Chocotejas.webp',
    description: 'Desde Perú traemos las auténticas Chocotejas: bombones artesanales rellenos de manjar blanco, frutas confitadas o nueces, cubiertos con una capa gruesa de chocolate oscuro. Una explosión de tradición y sabor en cada pieza.'
  },
  {
    id: 13,
    name: 'Chocolate con Fresa',
    category: 'Chocolatería',
    price: 58,
    image: '/Img/Products/Chocolateria/Chocolate_con_Fresa.webp',
    description: 'Nuestro Chocolate con Fresa combina el dulzor del chocolate con la acidez natural de las fresas liofilizadas. Es una fusión ideal para quienes aman los contrastes suaves y afrutados.'
  },
  {
    id: 14,
    name: 'Chocolate con Café',
    category: 'Chocolatería',
    price: 60,
    image: '/Img/Products/Chocolateria/Chocolate_con_Cafe.webp',
    description: 'Una combinación estimulante y deliciosa. El Chocolate con Café fusiona granos de café tostados con cacao de alta calidad, ofreciendo un sabor intenso, amargo y aromático que encantará a los más cafeteros.'
  },
  {
    id: 15,
    name: 'Chocolate con Pistache',
    category: 'Chocolatería',
    price: 63,
    image: '/Img/Products/Chocolateria/Chocolate_con_Pistache.webp',
    description: 'El sabor tostado y salado del pistache se une al dulzor del chocolate para crear una experiencia crujiente, equilibrada y adictiva. Ideal para los amantes de las nueces y de los sabores gourmet.'
  },
  {
    id: 16,
    name: 'Chocolate con Coco',
    category: 'Chocolatería',
    price: 59,
    image: '/Img/Products/Chocolateria/Chocolate_con_Coco.webp',
    description: 'La combinación del chocolate con la textura y sabor dulce del coco rallado crea una barra cremosa y tropical. Un placer que evoca playas y momentos relajados.'
  },
  {
    id: 17,
    name: 'Chocolate Orgánico',
    category: 'Chocolatería',
    price: 68,
    image: '/Img/Products/Chocolateria/Chocolate_Organico.webp',
    description: 'Elaborado con ingredientes 100% orgánicos, este chocolate es para quienes cuidan su salud y el planeta. Tiene un sabor puro y limpio que refleja la calidad del cacao seleccionado.'
  },
  {
    id: 18,
    name: 'Chocolate con Avellanas',
    category: 'Chocolatería',
    price: 65,
    image: '/Img/Products/Chocolateria/Chocolate_con_Avellanas.webp',
    description: 'El clásico favorito: chocolate suave combinado con trozos crujientes de avellanas tostadas. Ideal para un snack energético y delicioso.'
  },
  {
    id: 19,
    name: 'Chocolate de Leche',
    category: 'Chocolatería',
    price: 50,
    image: '/Img/Products/Chocolateria/Chocolate_de_Leche.webp',
    description: 'Con una textura cremosa y un sabor dulce suave, el Chocolate de Leche es una opción clásica que encanta a grandes y chicos.'
  },
  {
    id: 20,
    name: 'Chocolate con Caramelo',
    category: 'Chocolatería',
    price: 62,
    image: '/Img/Products/Chocolateria/Chocolate_con_Caramelo.webp',
    description: 'Una barra que combina el dulzor del chocolate con un relleno suave y pegajoso de caramelo, ofreciendo un contraste irresistible en cada mordida.'
  },
  {
    id: 66,
    name: 'Malvaviscos en Forma de Corazón',
    category: 'Malvaviscos',
    price: 25,
    image: '/Img/Products/Malvaviscos/Malvaviscos_corazon.webp',
    description:
      'Inspirados en el amor y la dulzura, los Malvaviscos en Forma de Corazón son una opción encantadora para fechas especiales como San Valentín, aniversarios o cualquier ocasión en la que quieras expresar cariño. Con una textura esponjosa y un sabor delicado, estos malvaviscos no solo deleitan el paladar, sino que también llenan de ternura cualquier mesa. Son ideales para envolver como regalo, decorar cajas de dulces, incluir en desayunos sorpresa o usar en repostería romántica. Su atractivo visual los convierte en una pieza central que roba miradas y corazones por igual.',
  },
  {
    id: 67,
    name: 'Malvaviscos Blancos',
    category: 'Malvaviscos',
    price: 50,
    image: '/Img/Products/Malvaviscos/malvaviscos_blancos.webp',
    description: '',
  },
  {
    id: 68,
    name: 'Malvaviscos Cítricos',
    category: 'Malvaviscos',
    price: 55,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Cítricos.webp',
    description: '',
  },
  {
    id: 69,
    name: 'Malvaviscos con Relleno',
    category: 'Malvaviscos',
    price: 60,
    image: '/Img/Products/Malvaviscos/Malvaviscos_con_Relleno.webp',
    description: '',
  },
  {
    id: 70,
    name: 'Malvaviscos Corazón',
    category: 'Malvaviscos',
    price: 65,
    image: '/Img/Products/Malvaviscos/Malvaviscos_corazon.webp',
    description: '',
  },
  {
    id: 71,
    name: 'Malvaviscos Cubiertos',
    category: 'Malvaviscos',
    price: 70,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Cubiertos.webp',
    description: '',
  },
  {
    id: 72,
    name: 'Malvaviscos de Colores',
    category: 'Malvaviscos',
    price: 55,
    image: '/Img/Products/Malvaviscos/Malvaviscos_de_Colores.webp',
    description: '',
  },
  {
    id: 73,
    name: 'Malvaviscos Decorativos',
    category: 'Malvaviscos',
    price: 60,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Decorativos.webp',
    description: '',
  },
  {
    id: 74,
    name: 'Malvaviscos Espolvoreados',
    category: 'Malvaviscos',
    price: 50,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Espolvoreados.webp',
    description: '',
  },
  {
    id: 75,
    name: 'Malvaviscos Estrella',
    category: 'Malvaviscos',
    price: 55,
    image: '/Img/Products/Malvaviscos/Malvaviscos_estrella.webp',
    description: '',
  },
  {
    id: 76,
    name: 'Malvaviscos Fresa',
    category: 'Malvaviscos',
    price: 60,
    image: '/Img/Products/Malvaviscos/malvaviscos_fresa.webp',
    description: '',
  },
  {
    id: 77,
    name: 'Malvaviscos Gigantes',
    category: 'Malvaviscos',
    price: 70,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Gigantes.webp',
    description: '',
  },
  {
    id: 78,
    name: 'Malvaviscos Surtidos',
    category: 'Malvaviscos',
    price: 65,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Surtidos.webp',
    description: '',
  },
  {
    id: 79,
    name: 'Malvaviscos Tostados',
    category: 'Malvaviscos',
    price: 60,
    image: '/Img/Products/Malvaviscos/Malvaviscos_Tostados.webp',
    description: '',
  },
  {
    id: 80,
    name: 'Malvaviscos XL',
    category: 'Malvaviscos',
    price: 80,
    image: '/Img/Products/Malvaviscos/Malvaviscos_XL.webp',
    description: '',
  },
{
    id: 81,
    name: 'Bigote',
    category: 'Panadería',
    price: 12,
    image: '/Img/Products/Panadería/bigote2.webp',
    description: '',
  },
  {
    id: 82,
    name: 'Bolillo',
    category: 'Panadería',
    price: 5,
    image: '/Img/Products/Panadería/bolillo.webp',
    description: '',
  },
  {
    id: 83,
    name: 'Cocol',
    category: 'Panadería',
    price: 10,
    image: '/Img/Products/Panadería/cocol.webp',
    description: '',
  },
  {
    id: 84,
    name: 'Concha',
    category: 'Panadería',
    price: 10,
    image: '/Img/Products/Panadería/concha.webp',
    description: '',
  },
  {
    id: 85,
    name: 'Cuernito',
    category: 'Panadería',
    price: 10,
    image: '/Img/Products/Panadería/cuernito.webp',
    description: '',
  },
  {
    id: 86,
    name: 'Empanada de Piña',
    category: 'Panadería',
    price: 12,
    image: '/Img/Products/Panadería/empanada de pina.webp',
    description: '',
  },
  {
    id: 87,
    name: 'Mantecada',
    category: 'Panadería',
    price: 10,
    image: '/Img/Products/Panadería/MANTECADAS2.webp',
    description: '',
  },
  {
    id: 88,
    name: 'Orejas',
    category: 'Panadería',
    price: 12,
    image: '/Img/Products/Panadería/orejas.webp',
    description: '',
  },
  {
    id: 89,
    name: 'Pan Danés',
    category: 'Panadería',
    price: 14,
    image: '/Img/Products/Panadería/pan danes.webp',
    description: '',
  },
  {
    id: 90,
    name: 'Pan de Elote',
    category: 'Panadería',
    price: 15,
    image: '/Img/Products/Panadería/pan de elote.webp',
    description: '',
  },
  {
    id: 91,
    name: 'Pan Relleno',
    category: 'Panadería',
    price: 14,
    image: '/Img/Products/Panadería/pan relleno.webp',
    description: '',
  },
  {
    id: 92,
    name: 'Pan de Muerto',
    category: 'Panadería',
    price: 15,
    image: '/Img/Products/Panadería/pan-de-muerto.webp',
    description: '',
  },
  {
    id: 93,
    name: 'Pan de Queso 2',
    category: 'Panadería',
    price: 14,
    image: '/Img/Products/Panadería/pandequeso2.webp',
    description: '',
  },
  {
    id: 94,
    name: 'Pan Integral',
    category: 'Panadería',
    price: 13,
    image: '/Img/Products/Panadería/panintegral2.webp',
    description: '',
  },
  {
    id: 95,
    name: 'Panqueso',
    category: 'Panadería',
    price: 14,
    image: '/Img/Products/Panadería/panqueso.webp',
    description: '',
  },
  {
    id: 96,
    name: 'Trenza de Chocolate',
    category: 'Panadería',
    price: 16,
    image: '/Img/Products/Panadería/trenza de chocolate.webp',
    description: '',
  },
{
    id: 97,
    name: 'Brownie',
    category: 'Postres',
    price: 20,
    image: '/Img/Products/Postres/brownie.webp',
    description: '',
  },
  {
    id: 98,
    name: 'Cheesecake',
    category: 'Postres',
    price: 25,
    image: '/Img/Products/Postres/Cheesecake.webp',
    description: '',
  },
  {
    id: 99,
    name: 'Churros Rellenos',
    category: 'Postres',
    price: 18,
    image: '/Img/Products/Postres/churros-rellenos.webp',
    description: '',
  },
  {
    id: 100,
    name: 'Cupcake',
    category: 'Postres',
    price: 15,
    image: '/Img/Products/Postres/cupcake.webp',
    description: '',
  },
  {
    id: 101,
    name: 'Mousse de Chocolate',
    category: 'Postres',
    price: 22,
    image: '/Img/Products/Postres/El_mousse_de_chocolate.webp',
    description: '',
  },
  {
    id: 102,
    name: 'Flan Napolitano',
    category: 'Postres',
    price: 20,
    image: '/Img/Products/Postres/flannapolitano.webp',
    description: '',
  },
  {
    id: 103,
    name: 'Galletas Decoradas',
    category: 'Postres',
    price: 18,
    image: '/Img/Products/Postres/galletas-decoradas.webp',
    description: '',
  },
  {
    id: 104,
    name: 'Gelatina',
    category: 'Postres',
    price: 12,
    image: '/Img/Products/Postres/gelatina.webp',
    description: '',
  },
  {
    id: 105,
    name: 'Helado Artesanal',
    category: 'Postres',
    price: 25,
    image: '/Img/Products/Postres/Helado Artesanal.webp',
    description: '',
  },
  {
    id: 106,
    name: 'Pastel de Chocolate',
    category: 'Postres',
    price: 35,
    image: '/Img/Products/Postres/Pastel de chocolate.webp',
    description: '',
  },
  {
    id: 107,
    name: 'Pastel Tres Leches',
    category: 'Postres',
    price: 38,
    image: '/Img/Products/Postres/pastel_TRES_LECHES.webp',
    description: '',
  },
  {
    id: 108,
    name: 'Pastel de Zanahoria',
    category: 'Postres',
    price: 35,
    image: '/Img/Products/Postres/Pastel-De-Zanahoria.webp',
    description: '',
  },
  {
    id: 109,
    name: 'Pay de Limón',
    category: 'Postres',
    price: 30,
    image: '/Img/Products/Postres/PayDeLimon.webp',
    description: '',
  },
  {
    id: 110,
    name: 'Tiramisú',
    category: 'Postres',
    price: 32,
    image: '/Img/Products/Postres/Tiramisu.webp',
    description: '',
  },
  {
    id: 111,
    name: 'Torta de Frutas',
    category: 'Postres',
    price: 36,
    image: '/Img/Products/Postres/TortaDeFrutas.webp',
    description: '',
  },
{
    id: 112,
    name: 'Caramelo Surtido',
    category: 'Dulces',
    price: 10,
    image: '/Img/Products/Dulces/Caramelo-surtido.webp',
    description: '',
  },
  {
    id: 113,
    name: 'Caramelos Relleno',
    category: 'Dulces',
    price: 12,
    image: '/Img/Products/Dulces/caramelos-relleno.webp',
    description: '',
  },
  {
    id: 114,
    name: 'Chicles',
    category: 'Dulces',
    price: 8,
    image: '/Img/Products/Dulces/chicles.webp',
    description: '',
  },
  {
    id: 115,
    name: 'Dulce de Leche',
    category: 'Dulces',
    price: 10,
    image: '/Img/Products/Dulces/dulce_de_leche.webp',
    description: '',
  },
  {
    id: 116,
    name: 'Dulces Picantes',
    category: 'Dulces',
    price: 10,
    image: '/Img/Products/Dulces/Dulces_Picantes.webp',
    description: '',
  },
  {
    id: 117,
    name: 'Dulces Ácidos',
    category: 'Dulces',
    price: 9,
    image: '/Img/Products/Dulces/dulces-acidos.webp',
    description: '',
  },
  {
    id: 118,
    name: 'Dulces de Menta',
    category: 'Dulces',
    price: 8,
    image: '/Img/Products/Dulces/dulces-menta.webp',
    description: '',
  },
  {
    id: 119,
    name: 'Duvalín',
    category: 'Dulces',
    price: 6,
    image: '/Img/Products/Dulces/duvalin.webp',
    description: '',
  },
  {
    id: 120,
    name: 'Gomitas Ácidas',
    category: 'Dulces',
    price: 10,
    image: '/Img/Products/Dulces/gomitas-acidas.webp',
    description: '',
  },
  {
    id: 121,
    name: 'Gomitas de Fruta',
    category: 'Dulces',
    price: 10,
    image: '/Img/Products/Dulces/Gomitas-de-Fruta.webp',
    description: '',
  },
  {
    id: 122,
    name: 'Mazapán',
    category: 'Dulces',
    price: 7,
    image: '/Img/Products/Dulces/mazapan.webp',
    description: '',
  },
  {
    id: 123,
    name: 'Paletas de Sabores',
    category: 'Dulces',
    price: 9,
    image: '/Img/Products/Dulces/paletas_de_sabores.webp',
    description: '',
  },
  {
    id: 124,
    name: 'Pulparindo',
    category: 'Dulces',
    price: 6,
    image: '/Img/Products/Dulces/Pulparindo.webp',
    description: '',
  },
  {
    id: 125,
    name: 'Rollitos de Fruta',
    category: 'Dulces',
    price: 8,
    image: '/Img/Products/Dulces/rollitos_de_fruta.webp',
    description: '',
  },
  {
    id: 126,
    name: 'Tamarindo Picante',
    category: 'Dulces',
    price: 10,
    image: '/Img/Products/Dulces/Tamarindo-Picante.webp',
    description: '',
  }
];


export default productsData;